# Generated by Django 4.2.6 on 2023-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('cost', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('video', models.URLField(null=True)),
                ('actuality', models.CharField(choices=[('Актуален', 'Актуален'), ('50 на 50', '50 на 50')], default=('Актуален', 'Актуален'), max_length=100, null=True)),
            ],
        ),
    ]
