# Generated by Django 4.2.6 on 2023-10-17 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_created_date_book_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_date_lang',
        ),
        migrations.AddField(
            model_name='book',
            name='actuality',
            field=models.CharField(choices=[('Актуален', 'Актуален'), ('50 на 50', '50 на 50')], default=('Актуален', 'Актуален'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cost',
            field=models.CharField(default=datetime.datetime(2023, 10, 17, 14, 16, 38, 498691, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
