# Generated by Django 4.2.6 on 2023-10-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_reviewbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewbook',
            name='title_lang',
        ),
    ]
